site_name: OSG Collaboration Support
site_url: https://opensciencegrid.org/collaboration-support
repo_name: https://github.com/opensciencegrid/collaboration-support
theme: 
  name: material

pages:
  - Home: 'index.md'
  - Current Collaborations:
    - Overview: 'projects/project-list.md'
    - REDTOP: 'projects/Redtop.md'
    - IceCube: 'projects/icecube.md'
    - LIGO: 'projects/ligo.md'
    - LSST: 'projects/lsst.md'
    - South Pole Telescope: 'projects/spt.md'
    - VERITAS: 'projects/veritas.md'
    - XENON: 'projects/xenon.md'
  - Meeting/Call schedule: 'misc/meeting-schedule.md'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: False
  - toc:
      permalink: True
